# Generated by Django 3.0.8 on 2020-07-06 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20200706_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumb_pic',
            field=models.ImageField(blank=True, default='moon.jpeg', upload_to=''),
        ),
    ]
